version: "3.6"
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:
  cuahangdb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=cuahangshop
      - MONGO_INITDB_ROOT_USERNAME=nguyenphuan
      - MONGO_INITDB_ROOT_PASSWORD=anbmt113
    expose:
      - 27017

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=27017
      - DB_HOST=cuahangdb
    ports:
      - 8080:8080
